### ISSUE TITLE
Cannot create Vault after building another time

### ISSUE THREAD

**Issue by chk-profiq** [MainframeHQ/mainframe-os#165]
There is error thrown when building and setting up the Mainframe OS more than once. 
There is probably some config that stores the environments and first vault data, that i could not find. I tried deleting the whole js-mainframe cloned repository, deleting mainframe environments from Library/Preferences or AppData. Setting everything up from scratch and could not get it working. 
Could You help me with this one? I found out that when building on new PC/OS everything goes well.
When creating from CLI i get these errors:
vault:create=>
```
   RPCError: The "size" argument must be of type number. Received type undefined
    at Function.fromObject (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/@mainframe/rpc-error/cjs/index.js:51:12)
    at Object.next (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/@mainframe/rpc-stream/cjs/index.js:67:43)
    at SafeSubscriber.__tryOrUnsub (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/rxjs/internal/Subscriber.js:209:16)
    at SafeSubscriber.next (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/rxjs/internal/Subscriber.js:147:22)
    at Subscriber._next (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/rxjs/internal/Subscriber.js:90:26)
    at Subscriber.next (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/rxjs/internal/Subscriber.js:67:18)
    at Subject.next (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/rxjs/internal/Subject.js:60:25)
    at Object.on.value (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/rx-socket/lib/index.js:76:18)
    at C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/oboe/dist/oboe-node.js:2322:25
    at apply (C:/Users/Christian-profiq/Documents/js-mainframe/packages/client/node_modules/oboe/dist/oboe-node.js:171:14)
```

client:setup =>

```
   (node:1020) UnhandledPromiseRejectionWarning: Error: Not connected
    at C:\Users\Christian-profiq\Documents\js-mainframe\packages\client\node_modules\@mainframe\rpc-stream\cjs\index.js:168:16
    at new Promise (<anonymous>)
    at StreamRPC.request (C:\Users\Christian-profiq\Documents\js-mainframe\packages\client\node_modules\@mainframe\rpc-stream\cjs\index.js:156:12)
    at VaultAPIs.create (C:\Users\Christian-profiq\Documents\js-mainframe\packages\client\lib\apis\Vault.js:8:22)
    at SetupCommand.createVault (C:\Users\Christian-profiq\Documents\js-mainframe\packages\cli\lib\Command.js:56:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks!

**Comment by canadaduane** [comment]
Thanks for reporting this. Are these two separate traces, or just one? I see `vault:create` there, and then `client:setup`... so it appears to be two commands, but if that's the case, I don't see what I would expect to be in the trace for an error coming from `client:setup`.

**Comment by chk-profiq** [comment]
Yeah, sorry. I updated it. I hope it is clear now.

**Comment by chk-profiq** [comment]
After this pull request https://github.com/MainframeHQ/js-mainframe/pull/167 the problem with connection after client:setup is fixed. However the error with "size" (probably some RPC config problem) is still present after both commands.
